#!/usr/bin/env python3
"""
Generate a weekly newsletter draft from papers added in the last 7 days.
Requires ANTHROPIC_API_KEY environment variable.
Output: newsletters/YYYY-MM-DD.md
"""
import json, os, sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import anthropic
except ImportError:
    print("anthropic not installed — skipping newsletter generation", file=sys.stderr)
    sys.exit(0)

PAPERS_FILE = Path(__file__).parent.parent / "src" / "data" / "papers.json"
OUT_DIR     = Path(__file__).parent.parent / "newsletters"
OUT_DIR.mkdir(exist_ok=True)

API_KEY = os.environ.get("ANTHROPIC_API_KEY")
if not API_KEY:
    print("ANTHROPIC_API_KEY not set — skipping", file=sys.stderr)
    sys.exit(0)

papers = json.loads(PAPERS_FILE.read_text())
cutoff = datetime.now(timezone.utc) - timedelta(days=7)

recent = [
    p for p in papers
    if p.get("added_at") and datetime.fromisoformat(p["added_at"].rstrip("Z")).replace(tzinfo=timezone.utc) >= cutoff
    and p.get("title")
]

today = datetime.now().strftime("%Y-%m-%d")
out_path = OUT_DIR / f"{today}.md"

if not recent:
    out_path.write_text(f"# SRT Research Digest — {today}\n\nNo new papers added this week.\n")
    print(f"No new papers. Wrote empty digest to {out_path}")
    sys.exit(0)

paper_list = "\n".join(
    f"- **{p['title']}** ({p.get('year','?')}) — simulants: {', '.join(p.get('simulants') or ['general'])}\n  {p['url']}"
    for p in recent
)

prompt = f"""You are writing the weekly research digest for Space Resource Technologies (SRT),
a company that manufactures regolith simulants (LHS-1, MGS-1, JEZ-1, etc.) for space research.

Write a short, professional newsletter digest (plain markdown) summarizing these {len(recent)} new papers
added to our database this week. Group them by simulant where possible.
Keep it concise — 1-2 sentences per paper. Include a brief intro and sign-off.

Papers:
{paper_list}
"""

client = anthropic.Anthropic(api_key=API_KEY)
msg = client.messages.create(
    model="claude-opus-4-7",
    max_tokens=1500,
    messages=[{"role": "user", "content": prompt}]
)

draft = msg.content[0].text.strip()

output = f"""---
date: {today}
papers_added: {len(recent)}
---

{draft}

---
*{len(recent)} paper(s) added this week · Generated by SRT Research Bot*
"""

out_path.write_text(output)
print(f"Newsletter draft written to {out_path} ({len(recent)} papers)")
